default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v1.2.5.a10
    hooks:
      - id: cfn-python-lint
        args:
          - "-i=E0000"
          - "-i=E1001"
          - "-i=E3012"
          - "-i=W6001"
        exclude: |
          (?x)(
            ^temp/|
            ^.circleci/|
            ^.pre-commit-config.yaml
          )
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.10
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'
    hooks:
      - id: poetry-check
      - id: poetry-lock
        language_version: python3.10
  - repo: https://github.com/AleksaC/circleci-cli-py
    rev: v0.1.30549
    hooks:
      - id: circle-ci-validator
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.0'
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [types-PyYAML]
